application: simplenotes
version: 1
runtime: python
api_version: 1

builtins:

- datastore_admin: on

handlers:

- url: /css
  static_dir: css

- url: /images/(.*\.(gif|jpg|png))
  static_files: images/\1
  upload: images/(.*\.(gif|jpg|png))
  expiration: 5h

- url: .*
  script: app.py
